import json
from datetime import datetime

from scanner.domain.models import Finding, ScanReport


class BaseReporter:
    name = "base"

    def render(self, report: ScanReport) -> str:
        raise NotImplementedError


class JSONReporter(BaseReporter):
    name = "json"

    def render(self, report: ScanReport) -> str:
        return json.dumps(
            report.model_dump(mode="json"),
            indent=2,
            default=str,
        )


class MarkdownReporter(BaseReporter):
    name = "markdown"

    def render(self, report: ScanReport) -> str:
        lines = [
            "# Prompt Injection Scan Report",
            "",
            f"**URL:** {report.url}",
            f"**Date:** {report.timestamp.isoformat()}",
            f"**Duration:** {report.scan_time_ms}ms",
            "",
            "## Risk Assessment",
            "",
            "| Metric | Value |",
            "|--------|-------|",
            f"| Risk Score | {report.risk_score}/100 |",
            f"| Risk Category | {report.risk_category} |",
            f"| Total Findings | {report.total_findings} |",
            "",
        ]

        if report.findings:
            lines.append("## Findings")
            lines.append("")
            for f in report.findings:
                lines.append(f"### [{f.severity.upper()}] {f.title}")
                lines.append("")
                lines.append(f"- **Detector:** {f.detector}")
                lines.append(f"- **Confidence:** {f.confidence:.0%}")
                lines.append(f"- **Category:** {f.category}")
                lines.append(f"- **Description:** {f.description}")
                lines.append(f"- **Snippet:** `{f.snippet[:200]}`")
                if f.recommendation:
                    lines.append(f"- **Recommendation:** {f.recommendation}")
                lines.append("")

        lines.append("---")
        lines.append("*Generated by Prompt Injection Scanner v0.1.0*")
        return "\n".join(lines)


class SimpleReporter(BaseReporter):
    name = "simple"

    def render(self, report: ScanReport) -> str:
        lines = [
            f"URL: {report.url}",
            f"Risk: {report.risk_score}/100 ({report.risk_category})",
            f"Findings: {report.total_findings}",
            f"Time: {report.scan_time_ms}ms",
            "",
        ]
        if report.summary:
            lines.append(report.summary)
            lines.append("")

        if report.findings:
            lines.append("Findings:")
            for f in report.findings:
                lines.append(f"  [{f.severity:>8}] {f.title} ({f.detector})")
                lines.append(f"          {f.snippet[:120]}")

        return "\n".join(lines)
