from scanner.domain.models import Finding, PolicyRule, ScanReport


class PolicyGenerator:
    """Generates policy rules from scan findings.

    Rules can be exported in formats compatible with:
    - MCPGuard (YAML)
    - Generic guardrails (JSON)
    """

    def generate(self, report: ScanReport) -> list[PolicyRule]:
        rules = []

        for finding in report.findings:
            if finding.severity in ("critical", "high"):
                rule = self._finding_to_rule(finding)
                if rule:
                    rules.append(rule)

        return rules

    def _finding_to_rule(self, finding: Finding) -> PolicyRule | None:
        snippet = finding.snippet[:80].strip()
        if not snippet:
            return None

        return PolicyRule(
            id=f"PIS-{finding.id[:8]}" if finding.id else "PIS-unknown",
            type="block_content",
            description=finding.title[:100],
            trigger="text_contains",
            pattern=snippet,
            action="block" if finding.severity == "critical" else "inspect",
            severity=finding.severity,
        )

    def to_mcpguard_yaml(self, report: ScanReport) -> str:
        rules = self.generate(report)
        if not rules:
            return ""

        lines = [
            "# Generated by Prompt Injection Scanner",
            f"# Source: {report.url}",
            f"# Date: {report.timestamp.isoformat()}",
            "",
            'version: "1.0"',
            "rules:",
        ]

        for rule in rules:
            lines.append(f'  - id: "{rule.id}"')
            lines.append(f'    type: "{rule.type}"')
            lines.append(f'    description: "{rule.description}"')
            lines.append(f'    trigger: "{rule.trigger}"')
            lines.append(f'    pattern: "{rule.pattern}"')
            lines.append(f'    action: "{rule.action}"')
            lines.append(f'    severity: "{rule.severity}"')

        return "\n".join(lines)
